[package]
name = "libobs-recorder"
version = "2.0.0"
edition = "2021"
authors = ["FX"]
description = "Record a window or screen using libobs."
license = "GPL-2.0"

[workspace]
members = ["libobs-sys"]

[dependencies]
libobs-sys = { path = "./libobs-sys", optional = true }
serde = { version = "1.0.163", features = ["derive"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.48.0", optional = true, features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi"] }
[target.'cfg(target_os = "linux")'.dependencies]
# todo
[target.'cfg(target_os = "macos")'.dependencies]
# todo

[features]
default = ["types-only"]
full = ["dep:libobs-sys", "dep:windows"] # builds everything
types-only = [] # only builds the settings/types not the recorder itself
serde = ["dep:serde"] # imports the serde dependency and adds Serialize and Deserialize implementations to all settings/types
debug = ["full"] # prints a log to stdout - implies full because else there is nothing to log

[[example]]
name = "record"
required-features = ["full"]
