[package]
name = "libobs-recorder"
version = "2.0.0"
edition = "2021"
authors = ["FX"]
description = "Record a window or screen using libobs."
license = "GPL-2.0"

[lib]
name = "libobs_recorder"
path = "src/lib.rs"

[[bin]]
name = "extprocess_recorder"
path = "src/main.rs"

[dependencies]
intprocess-recorder = { path = "intprocess-recorder", features = ["full"] }
ipc-link = { path = "ipc-link" }

[workspace]
members = [
    "libobs-sys",
    "ipc-link",
    "intprocess-recorder",
]
