[package]
name = "libobs-recorder"
version = "2.0.0"
edition = "2021"
authors = ["FX"]
description = "Record a window or screen using libobs."
license = "GPL-2.0"

[workspace]
members = ["libobs-sys"]

[dependencies]
libobs-sys = { path = "./libobs-sys", optional = true }
serde = { version = "1.0.163", features = ["derive"], optional = true }

[target.'cfg(target_os = "windows")'.dev-dependencies]
windows = { version = "0.34.0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi"] }
[target.'cfg(target_os = "linux")'.dev-dependencies]
# todo
[target.'cfg(target_os = "macos")'.dev-dependencies]
# todo

[features]
default = ["types-only"]
full = ["dep:libobs-sys"] # builds everything
types-only = [] # only builds the settings/types not the recorder itself
serde = ["dep:serde"] # imports the serde dependency and adds Serialize and Deserialize implementations to all settings/types
debug = ["full"] # prints a log to stdout - implies because else there is nothing to log

[[example]]
name = "record"
required-features = ["full"]
