[package]
name = "libobs-recorder"
version = "2.0.0"
edition = "2021"
authors = ["FX"]
description = "Record a window or screen using libobs."
license = "GPL-2.0"

[dependencies]
libobs-sys = { path = "./libobs-sys" }

[target.'cfg(target_os = "windows")'.dev-dependencies]
windows = { version = "0.34.0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi"] }
[target.'cfg(target_os = "linux")'.dev-dependencies]
# todo
[target.'cfg(target_os = "macos")'.dev-dependencies]
# todo

[features]
debug = []
