[package]
name = "libobs-recorder"
version = "0.1.0"
edition = "2021"
authors = ["FX"]
description = "Record a window or screen using libobs."

[dependencies]
libobs-sys = { path = "./libobs-sys" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.34.0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(unix)'.dependencies]
# todo: get window size on unix

[target.'cfg(macos)'.dependencies]
# todo: get window size on macos

[features]
debug = []