[package]
name = "libobs-sys"
version = "0.1.0"
authors = ["FX"]
description = "FFI bindings for libobs"
links = "obs"
build = "build.rs"

[build-dependencies]
bindgen = { version = "0.69.1", optional = true }

[features]
bindgen = ["dep:bindgen"]
