[package]
name = "ipc-link"
version = "0.1.0"
edition = "2021"

[dependencies]
intprocess-recorder = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wait-timeout = { workspace = true }
