[package]
name = "ipc-link"
version = "0.1.0"
edition = "2021"

[dependencies]
intprocess-recorder = { path = "../intprocess-recorder", features = ["types-only", "serde"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
wait-timeout = "0.2.0"
